# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - libcairo2-dev
    - libfreetype6-dev
    - libffi-dev
    - libjpeg-dev
    - libpng-dev
    - libz-dev

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
